scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: expressapi
  scrape_interval: 5s
  static_configs:
  - targets: 
    - host.docker.internal:3000